apiVersion: v1
kind: PersistentVolume
metadata:
  name: palworld-server-{{ index .Values "service-port" }}-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "local-storage"
  local:
    path: /data/palworld-server/data-{{ index .Values "service-port" }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: nene-server.com/port-range
            operator: In
            values: [{{ index .Values "belone-port-range" }}]