apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: palworld-server-{{ index .Values "service-port" }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: "local-storage"
  volumeName: palworld-server-{{ index .Values "service-port" }}-pv
  accessModes: 
  - ReadWriteOnce
  resources: 
    requests:
      storage: 3Gi