apiVersion: v1
kind: Service
metadata:
  name: palworld-server-{{ index .Values "service-port" }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    name: palworld-server-{{ index .Values "service-port" }}
    server: palworld
spec:
  type: NodePort
  ports:
    - name: game-port
      port: 8211
      nodePort: {{ index .Values "service-port" }}
      targetPort: game-port
      protocol: UDP
  selector:
    name: palworld-server-{{ index .Values "service-port" }}
    server: palworld
